final_stopword_list = c(stopwords("english"), "microservice", "microservices", "service", "services", "use", "data", 
                        "application", "system", "systems", "architecture", "applications", "paper", "can", "based", 
                        "approach", "provide", "based", "using", "software", "twitter", "com", "architecture", "via", 
                        "new", "pic", "need", "want", "like", "one", "will", "development", "model", "models", "also", 
                        "architectures", "used", "present", "environment", "way", "app", "get", "project", "request", 
                        "different", "code", "also", "create", "great", "however", "run", "running", "multiple", "know", 
                        "now", "trying", "example", "micro", "two", "just", "file", "call", "make", "access", "ive", 
                        "another", "best", "question", "message", "don't", "dont", "build", "work", "thanks", "following",
                        "implementation", "enabling", "towards", "basic", "event", "projects", "check", "part", "aware",
                        # Scopus further iteration 1
                        "environments", "various", "devices", "users", "user", "within", "needed", "propose", 
                        "presents", "specific", "large", "developed", "solutions", "many",
                        "existing", "well", "small", "provides", "set", "level", "real", "oriented", "process", "proposed",
                        "information", "driven", "results", "approaches", 
                        "show", "processes", "number", "key", "high", "end", "current", "technology",
                        # Scopus further iteration 2
                        "platform", "design", "resources", "management", "time", "framework", "network", "research",
                        "components", "support", "analysis", "monitoring", "solution", "communication", "context", 
                        "computing", "complexity", "evolution", "open", "migration", "lightweight",
                        "engineering", "challenges", "requirements", "digitalization", "order", "due", "building", "providers", "first",
                        "needs", "business",
                        # STO further iteration
                        "im", "working", "see", "without", "case", "possible", "able", "etc", "every", "something", "currently",
                        "created", "works", "found", "looking", "right", "seems", "find", "id", "add", "main", "good", "say",
                        "think", "start", "files", "method", "idea", "since", "really", "understand", "handle", "cant", "getting",
                        "even", "change", "still", "store", "consul", "doesnt", "tried", "name", "update", "creating", "several",
                        "local", "inside", "class", "fine", "sure", "lets", "eg", "apps", "anyone", "try", "state", "project",
                        "may", "external", "common", "page", "info", "keep", "custom", "going", "layer", "available", "across",
                        "uses", "done", "point", "image", "share", "core", "already", "write", "send", "version",
                        "please", "help", "issue", "problem", "read", "better", "simple", "module", "go", "lot", "error", "single", "separate",
                        "post",
                        # Twitter further iteration 1
                        "talk", "learn", "tech", "developer", "programming", "vs", "world", "today", "us", "re", "next", "developers", "big",
                        "don", "dev", "de", "day", "news", "full", "much", "join", "nice", "live", "technologypic", "york",
                        "register", "week", "ready", "th", "ll", "latesting", "take", "look", "und", "london", "native", "talking",
                        "developing", "presentation", "top", "introduction", "watch", "team", "modern", "tomorrow", "ve", "started",
                        "speaking", "teams", "panel", "en", "must", "exhibit", "keynote", "der", "forward", "opportunities", "con", "series",
                        "journey",  "week", "teams", "register", "architect", "last",
                        # Twitter further iteration 2
                        "meetup", "book", "guide", "summit", "article", "blog", "slides", "workshop", "journal", "video", "job", "future",
                        "interesting", "talks", "cool", "awesome", "love", "things", "lessons", "manage", "managing", "podcast", "die", "principles",
                        "free", "easy", "people", "engineer", "webinar", "session", "trends", "practices", "benefits")